### ISSUE TITLE
Missing detailed instructions of how to configure the portal in microsoft azure or locally.

### ISSUE THREAD

**Issue by ceoaliongroo** [Azure/azure-oss-portal#1]
Information in the site http://www.jeff.wilcox.name/2015/11/azure-on-github is to much, could be confusing if want to do a quick deploy and start to test.

I deployed the `Azure oss portal` in Microsoft Azure service. After, trying to open the site, response with a an blank page.

I'm image is because missing configuration. 

Could be great have an article just explain the configuration of `Azure oss portal` in Microsoft Azure and Locally.

**Comment by chriskacerguis** [comment]
@ceoaliongroo Not sure your specifics, but check the Application logs.  I'm in the process of setting it up, and one thing that I found is that by default Azure doesn't allow Redis over non-ssl, but this tool cannot handle SSL right now for the Redis connection, so you will need to update it to use the non-ssl port

**Comment by ceoaliongroo** [comment]
Thanks @chriskacerguis I give up with azure oss portal, too complicate
