### ISSUE TITLE
Breakdown of current changes

### ISSUE THREAD

**Issue by VanVilon** [Azure/azure-oss-portal#2]
There is a problem for 'breakdown of current changes' chart when actual value didn't pass 0.
![image](https://cloud.githubusercontent.com/assets/8150964/12911115/4972a1c2-cf10-11e5-8b1e-2f8035518086.png)

As you can see on the left side of chart - all of the numbers are '0'. However the chart does not show any information about amount of money are exactly charged.

I can make a pull request for you if you tell me where can i find this functionality.

**Comment by jeffwilcox** [comment]
Hi,
It sounds like this is an issue with the Azure Portal itself. This repo is actually related to a GitHub portal, not the actual OSS portal.

Please use the `@AzureSupport` Twitter account to see if maybe they can help?
