### ISSUE TITLE
ACOM Team - API Access/webhook for contributor signup

### ISSUE THREAD

**Issue by pkefal** [Azure/azure-oss-portal#3]
Hi Jeff,

I was decided to open an issue here instead of sending an e-mail. We need to access and synchronize contributors to our repo with their Microsoft UPN or alias or any other info you can provide us so we can automatically add them to internal systems and provide them access like Keyvault operations and similar.

What's the best way to achieve that?

**Comment by yanbingms** [comment]
Hi Jeff,
I checked out the source, and found it's written in Jade. How to convert it to .Net version, such as ASP.NET? Or do you know any other place has Azure-oss-portal in C#. 
I found the Real Azure portal was written in HTML5. But this git project looks like completely another thing.

//Yan

**Comment by jeffwilcox** [comment]
@yanbingms, the application is implemented in Node.js, I'm not sure what rewriting the entire application would accomplish.

**Comment by jeffwilcox** [comment]
Closing, the feature @pkefal is asking for is available.
